language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hardgrdb/fibonnaci-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hardgrdb/fibonnaci-app-test npm test -- --coverage

after_success:
  - docker build -t hardgrdb/fibonacci-app ./client
  - docker build -t hardgrdb/fibonacci-nginx ./nginx
  - docker build -t hardgrdb/fibonacci-server ./server
  - docker build -t hardgrdb/fibonacci-worker ./worker

  # Login to Docker CLI to connect to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to DockerHub
  - docker push hardgrdb/fibonacci-app
  - docker push hardgrdb/fibonacci-nginx
  - docker push hardgrdb/fibonacci-server
  - docker push hardgrdb/fibonacci-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: fibonacci-app
  env: FibonacciApp-env
  bucket_name: elasticbeanstalk-us-east-1-434478805792
  bucket_path: fibonacci-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY